version: "3"

services:
  node_backed:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    environment:
      - PGUSER=postgres
      - PGPASSWORD=segredo
      - PGHOST=node_db
    depends_on:
      - node_db

  node_db:
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - meu-volume:/var/lib/postgresql/data

volumes:
  meu-volume: {}