version: "3"

services:
  node_backend:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    env_file:
      - backend.env
    depends_on:
      - node_db

  node_db:
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - meu-volume:/var/lib/postgresql/data

volumes:
  meu-volume: {}